//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_SO_NUOC
    {
        public int KH_MA { get; set; }
        public string KYGHI_MA { get; set; }
        public int CSN_MA { get; set; }
        public Nullable<double> CSN_MOI { get; set; }
        public Nullable<double> CSN_CU { get; set; }
        public Nullable<double> CSN_TIEUTHU { get; set; }
        public Nullable<double> CSN_TIEUTHU1 { get; set; }
        public Nullable<double> CSN_TIEUTHU2 { get; set; }
        public string TTPT_MA { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual KY_GHI KY_GHI { get; set; }
        public virtual TRANG_THAI_PT TRANG_THAI_PT { get; set; }
    }
}
