//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cty_CapNuocEntities : DbContext
    {
        public Cty_CapNuocEntities()
            : base("name=Cty_CapNuocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHI_SO_NUOC> CHI_SO_NUOC { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<DOI_TUONG> DOI_TUONG { get; set; }
        public virtual DbSet<DONGIA> DONGIAs { get; set; }
        public virtual DbSet<HINHTHUC_THANHTOAN> HINHTHUC_THANHTOAN { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<KHU_VUC> KHU_VUC { get; set; }
        public virtual DbSet<KY_GHI> KY_GHI { get; set; }
        public virtual DbSet<LO_TRINH> LO_TRINH { get; set; }
        public virtual DbSet<MAIN_MENU> MAIN_MENU { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBANs { get; set; }
        public virtual DbSet<PHUONG> PHUONGs { get; set; }
        public virtual DbSet<QUAN> QUANs { get; set; }
        public virtual DbSet<SUB_MENU> SUB_MENU { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TRANG_THAI> TRANG_THAI { get; set; }
        public virtual DbSet<TRANG_THAI_PT> TRANG_THAI_PT { get; set; }
        public virtual DbSet<VAITRO> VAITROes { get; set; }
    }
}
