//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACH_HANG()
        {
            this.CHI_SO_NUOC = new HashSet<CHI_SO_NUOC>();
        }
    
        public int KH_MA { get; set; }
        public string LT_MA { get; set; }
        public string HTTT_MA { get; set; }
        public string TT_MA { get; set; }
        public string DT_MA { get; set; }
        public string KV_MA { get; set; }
        public string KH_HOTEN { get; set; }
        public string KH_DIACHILAPDAT { get; set; }
        public string KH_DIACHITHANHTOAN { get; set; }
        public string KH_SDT { get; set; }
        public string KH_SOTK { get; set; }
        public string KH_TENNGANHANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_SO_NUOC> CHI_SO_NUOC { get; set; }
        public virtual DOI_TUONG DOI_TUONG { get; set; }
        public virtual HINHTHUC_THANHTOAN HINHTHUC_THANHTOAN { get; set; }
        public virtual KHU_VUC KHU_VUC { get; set; }
        public virtual TRANG_THAI TRANG_THAI { get; set; }
        public virtual LO_TRINH LO_TRINH { get; set; }
    }
}
