//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_MENU
    {
        public int SUB_ID { get; set; }
        public string VT_MA { get; set; }
        public Nullable<int> MAIN_ID { get; set; }
        public string SUB_NAME { get; set; }
        public string SUB_CONTROLLER { get; set; }
        public string SUB_ACTION { get; set; }
    
        public virtual MAIN_MENU MAIN_MENU { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
